version: "3.7"

services:
  calibre:
    image: linuxserver/calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    deploy:
      labels:
        - traefik.port=8083
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-calibre.localhost}
    volumes:
      - ${VOLUME_PATH}config:/config
      - ${VOLUME_PATH}books:/books

volumes:
  config:
  books:

networks:
  internal:
    driver: overlay
    attachable: true
  default:
    external: true
    name: traefik-net
