version: '3.7'

services:
  server:
    image: ethibox/commento:latest
    environment:
      - COMMENTO_ORIGIN=${SCHEME:-http}://${DOMAIN:-commento.localhost}
      - COMMENTO_PORT=8080
      - COMMENTO_POSTGRES=postgres://commento:myp@ssw0rd@postgres:5432/commento?sslmode=disable
      - COMMENTO_FORBID_NEW_OWNERS=${COMMENTO_FORBID_NEW_OWNERS:-false}
      - COMMENTO_SMTP_HOST=${COMMENTO_SMTP_HOST:-mail.service.host}
      - COMMENTO_SMTP_PORT=${COMMENTO_SMTP_PORT:-587}
      - COMMENTO_SMTP_USERNAME=${COMMENTO_SMTP_USERNAME:-noreply@ethibox.fr}
      - COMMENTO_SMTP_PASSWORD=${COMMENTO_SMTP_PASSWORD:-password}
      - COMMENTO_SMTP_FROM_ADDRESS=${COMMENTO_SMTP_FROM_ADDRESS:-noreply@ethibox.fr}
    deploy:
      labels:
        - traefik.port=8080
        - traefik.enable=true
        - traefik.frontend.passHostHeader=true
        - traefik.frontend.rule=Host:${DOMAIN:-commento.localhost}
    networks:
      - internal
      - traefik

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: commento
      POSTGRES_PASSWORD: myp@ssw0rd
    volumes:
      - ${VOLUME_PATH}postgres:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  postgres:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
