version: '3.7'

x-defaults: &defaults
  environment:
    - POSTGRESQL_HOST=postgresql
    - POSTGRESQL_ROOT_USER=postgres
    - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=discourse
    - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=discourse
    - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=myp@ssw0rd
    - DISCOURSE_POSTGRESQL_NAME=discourse
    - DISCOURSE_POSTGRESQL_USERNAME=discourse
    - DISCOURSE_POSTGRESQL_PASSWORD=myp@ssw0rd
    - DISCOURSE_HOSTNAME=${DOMAIN:-discourse.localhost}
    - DISCOURSE_USERNAME=${DISCOURSE_USERNAME:-admin}
    - DISCOURSE_PASSWORD=${DISCOURSE_PASSWORD:-myp@ssw0rd}
    - DISCOURSE_EMAIL=${DISCOURSE_EMAIL:-admin@example.com}
    - DISCOURSE_HOST=discourse
    - DISCOURSE_PORT=3000
    - SMTP_HOST=${SMTP_HOST}
    - SMTP_PORT=${SMTP_PORT}
    - SMTP_USER=${SMTP_USER}
    - SMTP_PASSWORD=${SMTP_PASSWORD}
    - SMTP_TLS=${SMTP_TLS:-yes}
    - SMTP_AUTH=${SMTP_AUTH:-login}

services:
  discourse:
    <<: *defaults
    image: bitnami/discourse:${VERSION:-2.4.2}
    volumes:
        - ${VOLUME_PATH}data:/bitnami
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=3000
        - traefik.frontend.rule=Host:${DOMAIN:-discourse.localhost}
    networks:
      - traefik
      - internal

  sidekiq:
    <<: *defaults
    image: bitnami/discourse:${VERSION:-2.4.2}
    command: nami start --foreground discourse-sidekiq
    volumes:
      - ${VOLUME_PATH}sidekiq:/bitnami
    networks:
      - internal

  postgresql:
    image: bitnami/postgresql:11
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ${VOLUME_PATH}postgres:/bitnami/postgresql
    networks:
      - internal

  redis:
    image: redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - internal

volumes:
  postgres:
  data:
  sidekiq:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
