# ./fathom user add --email=<email> --password=<password>

version: '3.7'

services:
  init:
    image: usefathom/fathom:${VERSION:-latest}
    command: cp -r /app/fathom /mnt/
    volumes:
      - ${VOLUME_PATH}fathom:/mnt
    deploy:
      restart_policy:
        condition: on-failure

  web:
    image: usefathom/fathom:${VERSION:-latest}
    volumes:
      - ${VOLUME_PATH}fathom:/app
    deploy:
      labels:
        - traefik.port=8080
        - traefik.frontend.rule=Host:${DOMAIN:-fathom.localhost}
        - traefik.enable=true
    networks:
      - traefik

volumes:
  fathom:

networks:
  traefik:
    external: true
    name: traefik-net
