# php artisan migrate --seed
# php artisan firefly:upgrade-database
# php artisan firefly:verify
# php artisan cache:clear

version: '3.7'

services: 
  app: 
    image: jc5x/firefly-iii:${VERSION:-release-4.8.2}
    environment: 
      - DB_HOST=postgres
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=myp@ssw0rd
      - DB_CONNECTION=pgsql
      - DB_PORT=5432
      - APP_KEY=S0m3R@nd0mStr1ngOf32Ch@rsEx@ctly
      - APP_ENV=${APP_ENV:-local}
      - TZ=Europe/Paris
      - APP_LOG_LEVEL=${APP_LOG_LEVEL:-notice}
      - APP_URL=${SCHEME:-http}://${DOMAIN:-firefly.localhost}
      - TRUSTED_PROXIES=**
    deploy:
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-firefly.localhost}
    volumes:
      - ${VOLUME_PATH}storage:/var/www/firefly-iii/storage/
    networks:
      - internal
      - traefik

  postgres:
    image: postgres:10
    environment: 
      - POSTGRES_DB=firefly
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=myp@ssw0rd
    volumes:
      - ${VOLUME_PATH}postgres:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  postgres:
  storage:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
