version: '3.7'

services:
  app:
    image: flectrahq/flectra:${VERSION:-v1.6.4}
    volumes:
      - ${VOLUME_PATH}config:/etc/flectra
    environment:
      - HOST=postgres
      - PASSWORD=myp@ssw0rd
      - USER=flectra
    deploy:
      labels:
        - traefik.port=7073
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-flectra.localhost}
    networks:
      - internal
      - traefik

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ${VOLUME_PATH}postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=flectra
      - POSTGRES_PASSWORD=myp@ssw0rd
      - POSTGRES_DB=flectra
    networks:
      - internal

volumes:
  postgres:
  config:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
