version: '3.7'

services:
  web:
    image: ghost:${VERSION:-3.17.1-alpine}
    volumes:
      - ${VOLUME_PATH}ghost:/var/lib/ghost/content
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - url=${SCHEME:-http}://${DOMAIN:-ghost.localhost}
      - mail__transport=${MAIL_TRANSPORT:-SMTP}
      - mail__from=${SMTP_FROM}
      - mail__options__host=${SMTP_HOST}
      - mail__options__name=${SMTP_HOST}
      - mail__options__port=${SMTP_PORT:-587}
      - mail__options__auth__user=${SMTP_USER}
      - mail__options__auth__pass=${SMTP_PASSWORD}
    deploy:
      labels:
        traefik.port: 2368
        traefik.frontend.rule: Host:${DOMAIN:-ghost.localhost}
        traefik.enable: "true"
        traefik.frontend.headers.customResponseHeaders: "X-Frame-Options: SAMEORIGIN||X-XSS-Protection: 1; mode=block||Strict-Transport-Security: max-age=31536000; includeSubDomains||X-Content-Type-Options: nosniff"
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M

volumes:
  ghost:

networks:
  default:
    external: true
    name: traefik-net
