version: '3.7'

services:
    gogs:
      image: gogs/gogs:${VERSION-0.11.91}
      user: root
      ports:
        - target: 22
          published: ${SSH_PORT:-10022}
          protocol: tcp
          mode: host
      volumes:
        - ${VOLUME_PATH}data:/data
      deploy:
        labels:
          - traefik.port=3000
          - traefik.enable=true
          - traefik.frontend.rule=Host:${DOMAIN:-gogs.localhost}
        resources:
          limits:
            memory: 100M
          reservations:
            memory: 100M

volumes:
  data:

networks:
  default:
    external: true
    name: traefik-net
