version: '3.7'

services:
  grafana:
    image: grafana/grafana:6.5.2
    user: root
    volumes:
      - ${VOLUME_PATH}grafana:/var/lib/grafana
    deploy:
      labels:
        - traefik.port=3000
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN_GRAFANA:-grafana.localhost}

volumes:
  grafana:

networks:
  default:
    external: true
    name: traefik-net
