version: "3.7"

services:
  server:
    image: habitica/habitica-auto:${VERSION:-4.81.1}
    command: bash -c "cp config.json.example config.json && node ./website/transpiled-babel/index.js"
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL:-noreply@ethibox.fr}
      - BASE_URL=${SCHEME:-http}://${DOMAIN:-habitica.localhost}
      - NODE_DB_URI=mongodb://mongo/habitrpg
    deploy:
      labels:
        - traefik.port=3000
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-habitica.localhost}
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    networks:
      - traefik
      - internal

  mongo:
    image: mongo:4.0.3
    volumes:
      - ${VOLUME_PATH}mongo:/data/db
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    networks:
      - internal

volumes:
  mongo:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
