version: '3.7'

services:
  web:
    image: huginn/huginn:latest
    environment:
      - DATABASE_HOST=mysql
      - HUGINN_DATABASE_NAME=huginn
      - HUGINN_DATABASE_USERNAME=huginn
      - HUGINN_DATABASE_PASSWORD=myp@ssw0rd
      - DO_NOT_SEED=true
    deploy:
      labels:
        - traefik.port=3000
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-huginn.localhost}
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
    networks:
      - internal
      - traefik

  mysql:
    image: mysql:5.7
    volumes:
      - ${VOLUME_PATH}mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=huginn
      - MYSQL_USER=huginn
      - MYSQL_PASSWORD=myp@ssw0rd
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    networks:
      - internal

volumes:
  mysql:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
