version: "3.7"

services:
  nginx:
    image: ethibox/nginx-proxy
    command:
      - /bin/sh
      - -c
      - |
        envsubst '$$NGINX_ROOT_PATH' < /etc/nginx/nginx.template > /etc/nginx/nginx.conf
        sed -i -e 's/app:9000/'$$STACK_NAME'_app:9000/g' /etc/nginx/nginx.conf
        sed -i -e 's/fastcgi_pass backend;/fastcgi_pass backend;\n            fastcgi_param HTTPS '$$HTTPS';/g' /etc/nginx/nginx.conf
        nginx -g 'daemon off;'
    environment:
      - NGINX_ROOT_PATH=/var/www/app/public
      - STACK_NAME={{ index .Service.Labels "com.docker.stack.namespace" }}
      - HTTPS=${HTTPS:-0}
    volumes:
      - ${VOLUME_PATH}storage:/var/www/app/storage
      - ${VOLUME_PATH}data:/var/www/app/public
    deploy:
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-invoiceninja.localhost}
    networks:
      - internal
      - traefik

  app:
    image: invoiceninja/invoiceninja:${VERSION:-alpine-4.5.18}
    command: /bin/sh -c "chown -R www-data:www-data /var/www/app/ && php-fpm"
    volumes:
      - ${VOLUME_PATH}storage:/var/www/app/storage
      - ${VOLUME_PATH}data:/var/www/app/public
    environment:
      - APP_LOCALE=fr
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_URL=${SCHEME:-http}://${DOMAIN:-invoiceninja.localhost}
      - REQUIRE_HTTPS=${REQUIRE_HTTPS:-false}
      - APP_KEY=${APP_KEY:-S0meR@nd0mStringS0meR@nd0mString}
      - APP_CIPHER=AES-256-CBC
      - LOCK_SENT_INVOICES=${LOCK_SENT_INVOICES:-false}
      - DB_USERNAME=invoiceninja
      - DB_PASSWORD=myp@ssw0rd
      - DB_HOST=mariadb
      - DB_DATABASE=invoiceninja
      - PRECONFIGURED_INSTALL=true
      - MAIL_HOST=${MAIL_HOST:-mail.service.host}
      - MAIL_USERNAME=${MAIL_USERNAME:-username}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-password}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION:-tls}
      - MAIL_DRIVER=${MAIL_DRIVER:-smtp}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME:-"My name"}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-noreply@ethibox.fr}
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    networks:
      - internal

  mariadb:
    image: mariadb:10.3.14
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=invoiceninja
      - MYSQL_USER=invoiceninja
      - MYSQL_PASSWORD=myp@ssw0rd
    networks:
      - internal

volumes:
  mariadb:
  data:
  storage:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
