version: '3.7'

services:
  web:
    image: jenkinsci/blueocean:${VERSION:-1.22.0}
    volumes:
      - ${VOLUME_PATH}data:/var/jenkins_home
    deploy:
      labels:
        - traefik.port=8080
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-jenkins.localhost}

volumes:
  data:

networks:
  default:
    external: true
    name: traefik-net
