version: '3.7'

services:
  kanboard:
    image: kanboard/kanboard:${VERSION:-v1.2.13}
    volumes:
      - ${VOLUME_PATH}data:/var/www/app/data
      - ${VOLUME_PATH}plugins:/var/www/app/plugins
    deploy:
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-kanboard.localhost}
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M

volumes:
  data:
  plugins:

networks:
  default:
    external: true
    name: traefik-net
