# apt-get update;apt-get install -y git
# COMPOSER_ALLOW_SUPERUSER=1 composer require mageplaza/magento-2-french-language-pack:dev-master
# php bin/magento setup:static-content:deploy -f fr_FR
# php bin/magento cache:flush

version: '3.7'

services:
  magento:
    image: bitnami/magento:${VERSION:-2.3.3}
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=magento
      - MAGENTO_DATABASE_PASSWORD=myp@ssw0rd
      - MAGENTO_DATABASE_NAME=magento
      - MAGENTO_HOST=${DOMAIN:-magento.localhost}
      - MAGENTO_MODE=production
    deploy:
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-magento.localhost}
    volumes:
      - ${VOLUME_PATH}magento:/bitnami
    networks:
      - traefik
      - internal

  mariadb:
    image: mariadb:10.3.14
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=magento
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql
    networks:
      - internal

volumes:
  mariadb:
  magento:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
