version: '3.7'

services:
  matomo:
    image: matomo:${VERSION:-3.13.4}
    environment:
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_DBNAME=matomo
      - MATOMO_DATABASE_PASSWORD=myp@ssw0rd
      - MATOMO_DATABASE_HOST=mariadb
    volumes:
      - ${VOLUME_PATH}config:/var/www/html/config
    deploy:
      labels:
        - traefik.port=80
        - traefik.frontend.rule=Host:${DOMAIN:-matomo.localhost}
        - traefik.enable=true
    networks:
      - traefik
      - internal

  mariadb:
    image: mariadb:10.3.10
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MYSQL_PASSWORD=myp@ssw0rd
    networks:
      - internal

volumes:
  mariadb:
  config:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
