version: '3.7'

services:
  web:
    image: ethibox/matterwiki:latest
    volumes:
      - ${VOLUME_PATH}data:/server/db
    deploy:
      labels:
        - traefik.port=5000
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-matterwiki.localhost}
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M

volumes:
  data:

networks:
  default:
    external: true
    name: traefik-net
