version: '3.7'

services:
  mautic:
    image: ethibox/mautic:${VERSION:-2.16.1}
    volumes:
      - ${VOLUME_PATH}data:/var/www/html
    environment:
      - MAUTIC_DB_HOST=mariadb
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_DB_USER=mautic
      - MAUTIC_DB_PASSWORD=myp@ssw0rd
      - MAUTIC_TRUSTED_PROXIES=0.0.0.0/0
    deploy:
      labels:
        - traefik.port=80
        - traefik.frontend.rule=Host:${DOMAIN:-mautic.localhost}
        - traefik.enable=true
    networks:
      - traefik
      - internal

  mariadb:
    image: mariadb:10.3.14
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=mautic
      - MYSQL_USER=mautic
      - MYSQL_PASSWORD=myp@ssw0rd
    networks:
      - internal

volumes:
  mariadb:
  data:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
