version: '3.7'

services:
  web:
    image: mediawiki:${VERSION:-1.33.1}
    volumes:
      - ${VOLUME_PATH}data:/var/www/html:cached
    deploy:
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-mediawiki.localhost}
    networks:
      - internal
      - traefik

  mariadb:
    image: mariadb:10.3.14
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=mediawiki
      - MYSQL_PASSWORD=myp@ssw0rd
    networks:
      - internal

volumes:
  data:
  mariadb:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
