version: '3.7'

services:
  metabase:
    image: metabase/metabase:${VERSION:-v0.34.2}
    deploy:
      labels:
        - traefik.port=3000
        - traefik.frontend.rule=Host:${DOMAIN:-metabase.localhost}
        - traefik.enable=true
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
    environment:
      - MB_DB_TYPE=mysql
      - MB_DB_HOST=mariadb
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=3306
      - MB_DB_USER=metabase
      - MB_DB_PASS=myp@ssw0rd
    networks:
      - internal
      - traefik

  mariadb:
    image: mariadb:10.3.12
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_USER=metabase
      - MYSQL_DATABASE=metabase
      - MYSQL_PASSWORD=myp@ssw0rd
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql
    networks:
      - internal

volumes:
  mariadb:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
