version: '3.7'

services:
  nginx:
    image: ethibox/nginx-proxy:latest
    command:
      - /bin/sh
      - -c
      - |
        usermod -u 82 www-data
        cp /etc/nginx/nginx-onlyoffice.conf /etc/nginx/nginx.conf
        sed -i -e 's/app:9000/'$$STACK_NAME'_app:9000/g' /etc/nginx/nginx.conf
        nginx -g 'daemon off;'
    environment:
      - STACK_NAME={{ index .Service.Labels "com.docker.stack.namespace" }}
    volumes:
      - ${VOLUME_PATH}nextcloud:/var/www/html:cached
    deploy:
      labels:
        traefik.enable: "true"
        traefik.port: 80
        traefik.frontend.rule: Host:${DOMAIN:-nextcloud.localhost}
        traefik.frontend.headers.customResponseHeaders: "X-Frame-Options: SAMEORIGIN||Strict-Transport-Security: max-age=31536000||Referrer-Policy: no-referrer"
        traefik.frontend.redirect.permanent: "true"
        traefik.frontend.redirect.regex: https://(.*)/.well-known/(card|cal)dav
        traefik.frontend.redirect.replacement: https://$$1/remote.php/dav/
    networks:
      - internal
      - traefik

  app:
    image: nextcloud:${VERSION:-18.0.1-fpm-alpine}
    command:
      - /bin/sh
      - -c
      - |
        sleep 10
        apk add --no-cache sudo
        sudo -u www-data php occ --no-warnings db:add-missing-indices
        sudo -u www-data php occ --no-warnings db:convert-filecache-bigint
        sudo -u www-data php occ --no-warnings config:system:set trusted_proxies 0 --value="172.xx.0.x"
        sudo -u www-data php occ --no-warnings config:system:set overwriteprotocol --value="${SCHEME:-http}"
        sudo -u www-data php occ --no-warnings config:system:set overwrite.cli.url --value="${SCHEME:-http}://${DOMAIN:-nextcloud.localhost}"
        sudo -u www-data php occ --no-warnings app:install onlyoffice
        sudo -u www-data php occ --no-warnings config:system:set onlyoffice DocumentServerUrl --value="/ds-vpath/"
        sudo -u www-data php occ --no-warnings config:system:set onlyoffice DocumentServerInternalUrl --value="http://onlyoffice/"
        sudo -u www-data php occ --no-warnings config:system:set onlyoffice StorageUrl --value="http://nginx/"
        php-fpm
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-admin}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-myp@ssw0rd}
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN:-nextcloud.localhost} nginx
      - NEXTCLOUD_UPDATE=1
    volumes:
      - ${VOLUME_PATH}nextcloud:/var/www/html:cached
    networks:
      - internal

  mariadb:
    image: mariadb:10.3.12
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-myp@ssw0rd}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql
    networks:
      - internal

  onlyoffice:
    image: onlyoffice/documentserver:5.4.2.46
    networks:
      - internal

volumes:
  nextcloud:
  mariadb:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
