version: '3.7'

services:
  passbolt:
    image: passbolt/passbolt:${VERSION:-2.12.1-debian}
    command: ["/usr/bin/wait-for.sh", "-t", "0", "mariadb:3306", "--", "/docker-entrypoint.sh"]
    environment:
      - APP_FULL_BASE_URL=${SCHEME:-http}://${DOMAIN:-passbolt.localhost}
      - DATASOURCES_DEFAULT_HOST=mariadb
      - DATASOURCES_DEFAULT_USERNAME=passbolt
      - DATASOURCES_DEFAULT_PASSWORD=myp@ssw0rd
      - DATASOURCES_DEFAULT_DATABASE=passbolt
      - DATASOURCES_DEFAULT_PORT=3306
    tmpfs:
      - /run
    volumes:
      - ${VOLUME_PATH}gpg:/var/www/passbolt/config/gpg
      - ${VOLUME_PATH}images:/var/www/passbolt/webroot/img/public
    deploy:
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-passbolt.localhost}
    networks:
      - internal
      - traefik

  mariadb:
    image: mariadb:10.3.14
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=passbolt
      - MYSQL_USER=passbolt
      - MYSQL_PASSWORD=myp@ssw0rd
    networks:
      - internal

volumes:
  gpg:
  images:
  mariadb:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
