version: '3.7'

services:
  agent:
    image: portainer/agent:1.5.1
    environment:
      - AGENT_CLUSTER_ADDR=tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global
    networks:
      - agent_network

  portainer:
    image: portainer/portainer:${VERSION:-1.24.1}
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - ${VOLUME_PATH}portainer:/data
    deploy:
      labels:
        - traefik.port=9000
        - traefik.frontend.rule=Host:${DOMAIN:-portainer.localhost}
        - traefik.enable=true
      mode: replicated
      replicas: 1
    networks:
      - agent_network
      - traefik

volumes:
  portainer:

networks:
  agent_network:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
