version: '3.7'

services:
  pydio:
    image: pydio/cells:2.0.1
    volumes:
      - ${VOLUME_PATH}data:/var/cells:cached
    environment:
      - CELLS_BIND=0.0.0.0:8080
      - CELLS_EXTERNAL=${SCHEME:-http}://${DOMAIN:-pydio.localhost}
      - CELLS_NO_TLS=1
    deploy:
      labels:
        - traefik.port=8080
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-pydio.localhost}
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
    networks:
      - internal
      - traefik

  mariadb:
    image: mariadb:10.3.14
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=pydio
      - MYSQL_USER=pydio
      - MYSQL_PASSWORD=myp@ssw0rd
    networks:
      - internal

volumes:
  data:
  mariadb:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
