version: '3.7'

services:
  rainloop:
    image: hardware/rainloop:latest
    volumes:
      - ${VOLUME_PATH}rainloop:/rainloop/data
    deploy:
      labels:
        - traefik.port=8888
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-rainloop.localhost}

networks:
  default:
    external: true
    name: traefik-net
