# Set enable_registration=true manually
# Set default_identity_server manually

version: '3.7'

services:
  web:
    image: vectorim/riot-web:${VERSION:-v1.5.15}
    command:
      - /bin/sh
      - -c
      - |
        sed -i -e 's#https://matrix-client.matrix.org#'$$SCHEME'://'$$DOMAIN'#g' /app/config.json
        sed -i -e 's/matrix.org/'$$DOMAIN'/g' /app/config.json
        sed -i -e 's/"breadcrumbs": true/"breadcrumbs": true,\n        "language": "'$$LANGUAGE'"/g' /app/config.json
        nginx -g 'daemon off;'
    environment:
      - DOMAIN=${DOMAIN:-riot.localhost}
      - SCHEME=${SCHEME:-http}
      - LANGUAGE=${LANGUAGE:-fr_FR}
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: Host:${DOMAIN:-riot.localhost}
        traefik.enable: "true"
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    networks:
      - traefik
      - internal

  synapse:
    image: matrixdotorg/synapse:v1.8.0
    volumes:
      - ${VOLUME_PATH}synapse:/data
    deploy:
      labels:
        traefik.port: 8008
        traefik.frontend.rule: Host:${DOMAIN:-riot.localhost};PathPrefix:/_matrix
        traefik.enable: "true"
    networks:
      - traefik
      - internal

  synapse-init:
    image: matrixdotorg/synapse:v1.8.0
    command: generate
    volumes:
      - ${VOLUME_PATH}synapse:/data
    environment:
      - SYNAPSE_SERVER_NAME=${DOMAIN:-riot.localhost}
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_NO_TLS=yes
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - internal

volumes:
  synapse:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
