version: '3.7'

services:
  web:
    image: rocketchat/rocket.chat:${VERSION:-3.2.1}
    command: bash -c 'for i in `seq 1 30`; do node --max-old-space-size=4096 main.js && s=$$? && break || s=$$?; echo "Tried $$i times. Waiting 5 secs..."; sleep 5; done; (exit $$s)'
    volumes:
      - ${VOLUME_PATH}uploads:/app/uploads
    environment:
      - ROOT_URL=${SCHEME:-http}://${DOMAIN:-rocketchat.localhost}
      - MONGO_URL=mongodb://mongo:27017/rocketchat?replicaSet=rs01
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local?replicaSet=rs01
    deploy:
      labels:
        - traefik.port=3000
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-rocketchat.localhost}
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 2m
    networks:
      - traefik
      - internal

  mongo:
    image: mongo:4.0.3
    command: mongod --smallfiles --oplogSize 128 --replSet rs01
    volumes:
      - ${VOLUME_PATH}mongo:/data/db
    networks:
      - internal

  mongo-init-replica:
    image: mongo:4.0.3
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs01'', members: [ { _id: 0, host: ''mongo:27017'' } ]})"'
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - internal

volumes:
  uploads:
  mongo:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
