version: '3.7'

services:
  web:
    image: searx/searx:latest
    deploy:
      labels:
        traefik.port: 8080
        traefik.frontend.rule: Host:${DOMAIN:-searx.localhost}
        traefik.enable: "true"
        traefik.frontend.headers.customResponseHeaders: "X-Frame-Options: SAMEORIGIN||X-XSS-Protection: 1; mode=block||Strict-Transport-Security: max-age=31536000; includeSubDomains||X-Content-Type-Options: nosniff"

networks:
  default:
    external: true
    name: traefik-net
