# Go to /admin/ to change default password admin:123123

version: '3.7'

services:
  back:
    image: dockertaiga/back:latest
    volumes:
      - ${VOLUME_PATH}media:/taiga-media
    environment:
      - TAIGA_HOST=${DOMAIN:-taiga.localhost}
      - TAIGA_SECRET=${TAIGA_SECRET:-secret}
      - TAIGA_SCHEME=${SCHEME:-http}
      - DB_HOST=db
      - DB_NAME=taiga
      - DB_USER=postgres
      - DB_PASSWORD=password
      - RABBIT_HOST=rabbit
      - RABBIT_USER=taiga
      - RABBIT_PASSWORD=password
      - RABBIT_VHOST=taiga
    networks:
      - internal

  front:
    image: dockertaiga/front:latest
    environment:
      - TAIGA_HOST=${DOMAIN:-taiga.localhost}
      - TAIGA_SCHEME=${SCHEME:-http}
    networks:
      - internal

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=taiga
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ${VOLUME_PATH}db:/var/lib/postgresql/data
    networks:
      - internal

  rabbit:
    image: dockertaiga/rabbit:latest
    environment:
      - RABBIT_USER=taiga
      - RABBIT_PASSWORD=password
      - RABBIT_VHOST=taiga
    networks:
      - internal

  events:
    image: dockertaiga/events:latest
    environment:
      - RABBIT_HOST=rabbit
      - RABBIT_VHOST=taiga
      - RABBIT_USER=taiga
      - RABBIT_PASSWORD=password
    networks:
      - internal

  proxy:
    image: dockertaiga/proxy:latest
    deploy:
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-taiga.localhost}
    environment:
      - TAIGA_HOST=${DOMAIN:-taiga.localhost}
      - TAIGA_BACK_HOST=back
      - TAIGA_FRONT_HOST=front
      - EVENTS_HOST=events
    networks:
      - internal
      - traefik

volumes:
  media:
  db:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
