# /entrypoint.sh trytond-admin -d tryton --all

version: "3.7"

services:
  tryton:
    image: tryton/tryton:${VERSION:-5.4}
    environment:
      - DB_USER=tryton
      - DB_PASSWORD=${DB_PASSWORD:-myp@ssw0rd}
      - DB_HOSTNAME=postgres
      - DB_PORT=5432
    volumes:
      - ${VOLUME_PATH}data:/var/lib/trytond/db
    deploy:
      labels:
        - traefik.port=8000
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-tryton.localhost}
    networks:
      - internal
      - traefik

  cron:
    image: tryton/tryton:${VERSION:-5.4}
    command: trytond-cron -d tryton
    environment:
      - DB_USER=tryton
      - DB_PASSWORD=${DB_PASSWORD:-myp@ssw0rd}
      - DB_HOSTNAME=postgres
      - DB_PORT=5432
    volumes:
      - ${VOLUME_PATH}data:/var/lib/trytond/db
    networks:
      - internal

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ${VOLUME_PATH}postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tryton
      - POSTGRES_PASSWORD=${DB_PASSWORD:-myp@ssw0rd}
      - POSTGRES_DB=tryton
    networks:
      - internal

volumes:
  postgres:
  data:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
