version: '3.7'

services:
  web:
    image: requarks/wiki:${VERSION:-2.0.12}
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=wikijs
      - DB_PASS=myp@ssw0rd
      - DB_NAME=wikijs
    deploy:
      labels:
        - traefik.port=3000
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-wikijs.localhost}
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    networks:
      - internal
      - traefik

  postgres:
    image: postgres:9-alpine
    environment:
      - POSTGRES_DB=wikijs
      - POSTGRES_PASSWORD=myp@ssw0rd
      - POSTGRES_USER=wikijs
    volumes:
      - ${VOLUME_PATH}postgres:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  postgres:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
