# sudo sysctl -w vm.max_map_count=262144
# echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf
# chown -R 1000:1000 elasticsearch

version: '3.7'

services:
  zammad-elasticsearch:
    image: zammad/zammad-docker-compose:zammad-elasticsearch-${VERSION:-3.3.0-11}
    environment:
      - discovery.type=single-node
    volumes:
      - ${VOLUME_PATH}elasticsearch:/usr/share/elasticsearch/data
    networks:
      - internal

  zammad-init:
    image: zammad/zammad-docker-compose:zammad-${VERSION:-3.3.0-11}
    command: ["zammad-init"]
    volumes:
      - ${VOLUME_PATH}zammad:/opt/zammad
    environment:
      - POSTGRESQL_PASS=myp@ssw0rd
      - POSTGRESQL_DB=zammad
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - internal

  zammad-memcached:
    image: memcached:1.5.22-alpine
    command: memcached -m 256M
    networks:
      - internal

  zammad-nginx:
    image: zammad/zammad-docker-compose:zammad-${VERSION:-3.3.0-11}
    command: ["zammad-nginx"]
    volumes:
      - ${VOLUME_PATH}zammad:/opt/zammad
    deploy:
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-zammad.localhost}
    networks:
      - traefik
      - internal

  zammad-postgresql:
    image: postgres:9.6-alpine
    volumes:
      - ${VOLUME_PATH}postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=zammad
      - POSTGRES_PASSWORD=myp@ssw0rd
      - POSTGRES_DB=zammad
    networks:
      - internal

  zammad-railsserver:
    image: zammad/zammad-docker-compose:zammad-${VERSION:-3.3.0-11}
    command: ["zammad-railsserver"]
    volumes:
      - ${VOLUME_PATH}zammad:/opt/zammad
    networks:
      - internal

  zammad-scheduler:
    image: zammad/zammad-docker-compose:zammad-${VERSION:-3.3.0-11}
    command: ["zammad-scheduler"]
    volumes:
      - ${VOLUME_PATH}zammad:/opt/zammad
    networks:
      - internal

  zammad-websocket:
    image: zammad/zammad-docker-compose:zammad-${VERSION:-3.3.0-11}
    command: ["zammad-websocket"]
    volumes:
      - ${VOLUME_PATH}zammad:/opt/zammad
    networks:
      - internal

volumes:
  zammad:
  elasticsearch:
  postgresql:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
