version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    #ports:
    #  - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin123 
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wordpress:/var/www/html

    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.wp-secure.entrypoints=websecure"
      - "traefik.http.routers.wp-secure.rule=Host(`redflox.com`)"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:

networks:
  proxy:
    external: true
